server.port=8080

spring.application.name=api-gateway

# =========================
# Spring Cloud Gateway
# =========================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://authentication-service:8091
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=device-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://device-service:8092
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/devices/**

spring.cloud.gateway.server.webmvc.routes[2].id=kelembapan-tanah-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://kelembapan-tanah-service:8094
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/kelembapan-tanah/**

spring.cloud.gateway.server.webmvc.routes[3].id=kelembapan-udara-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://kelembapan-udara-service:8095
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/kelembapan-udara/**

spring.cloud.gateway.server.webmvc.routes[4].id=ph-tanah-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://ph-tanah-service:8096
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/ph-tanah/**

spring.cloud.gateway.server.webmvc.routes[5].id=suhu-tanah-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://suhu-tanah-service:8097
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/suhu-tanah/**

spring.cloud.gateway.server.webmvc.routes[6].id=suhu-udara-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://suhu-udara-service:8098
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/suhu-udara/**

spring.cloud.gateway.server.webmvc.routes[7].id=dashboard-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://dashboard-service:8099
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/dashboard/**

spring.cloud.gateway.server.webmvc.routes[8].id=weekly-report-service
spring.cloud.gateway.server.webmvc.routes[8].uri=http://weekly-report-service:8100
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/reports/**

spring.cloud.gateway.server.webmvc.routes[9].id=notification-service
spring.cloud.gateway.server.webmvc.routes[9].uri=http://notification-service:8101
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/notifications/**

# =========================
# Eureka
# =========================

eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

# =========================
# Actuator
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# =========================
# Prometheus
# =========================

management.prometheus.metrics.export.enabled=true

# =========================
# Metrics
# =========================

management.metrics.tags.application=${spring.application.name}