services:
  prometheus:
    image: prom/prometheus

    container_name: prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - caliak-network

  grafana:
    image: grafana/grafana
    container_name: grafana

    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - caliak-network

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch

    restart: unless-stopped

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    networks:
      - caliak-network

  logstash:
    image: logstash:8.13.4
    container_name: logstash

    restart: unless-stopped

    depends_on:
      - elasticsearch

    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

    ports:
      - "5000:5000"

    networks:
      - caliak-network

  kibana:
    image: kibana:8.13.4
    container_name: kibana

    restart: unless-stopped

    depends_on:
      - elasticsearch

    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

    ports:
      - "5601:5601"

    networks:
      - caliak-network

networks:
  caliak-network:
    external: true
    name: deployment_caliak-network

volumes:
  grafana-data:
